In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn import datasets
cancer = datasets.load_breast_cancer()

In [ ]:
cancer.data.shape

(569, 30)

In [ ]:
df = pd.DataFrame(cancer.data, columns = cancer.feature_names)
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [ ]:
X = cancer.data
y = cancer.target

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=123)

In [ ]:
X_train

array([[1.151e+01, 2.393e+01, 7.452e+01, ..., 9.653e-02, 2.112e-01,
        8.732e-02],
       [1.377e+01, 1.327e+01, 8.806e+01, ..., 5.802e-02, 2.823e-01,
        6.794e-02],
       [1.719e+01, 2.207e+01, 1.116e+02, ..., 1.984e-01, 3.216e-01,
        7.570e-02],
       ...,
       [1.205e+01, 2.272e+01, 7.875e+01, ..., 1.092e-01, 2.191e-01,
        9.349e-02],
       [2.044e+01, 2.178e+01, 1.338e+02, ..., 1.765e-01, 2.609e-01,
        6.735e-02],
       [1.174e+01, 1.469e+01, 7.631e+01, ..., 1.056e-01, 2.604e-01,
        9.879e-02]])

In [ ]:
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)

In [ ]:
print(X_train)

[[0.19357291 0.46885813 0.19139445 ... 0.33171821 0.10782574 0.27365209]
 [0.3081251  0.1        0.28881854 ... 0.19938144 0.2479795  0.1093591 ]
 [0.48147397 0.40449827 0.45819542 ... 0.68178694 0.32544845 0.17514412]
 ...
 [0.22094379 0.42698962 0.22183048 ... 0.37525773 0.12339838 0.32595795]
 [0.64620609 0.39446367 0.61793064 ... 0.60652921 0.20579539 0.10435741]
 [0.20523088 0.14913495 0.204274   ... 0.3628866  0.20480978 0.37088844]]


In [ ]:
X_test = scaler.transform(X_test)

In [ ]:
print(X_test)

[[0.18039434 0.15224913 0.16880127 ... 0.05728522 0.24640252 0.16225839]
 [0.10395864 0.18304498 0.0977119  ... 0.17728522 0.2515277  0.22643269]
 [0.49921435 0.30934256 0.4833789  ... 0.66632302 0.26867731 0.20032214]
 ...
 [0.57676517 0.49930796 0.5783566  ... 0.85670103 0.61206387 0.41336046]
 [0.63302752 0.31695502 0.61793064 ... 0.7467354  0.289178   0.21795524]
 [0.1651883  0.37958478 0.17254281 ... 0.48934708 0.2757737  0.347745  ]]


In [ ]:
X_train.var()

0.0304444202098801

In [ ]:
from sklearn import svm

clf = svm.SVC(kernel='linear')


clf.fit(X_train, y_train)


y_pred = clf.predict(X_test)

In [ ]:
from sklearn import metrics

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9883040935672515


In [ ]:
y_pred_train = clf.predict(X_train)
print("Accuracy on Training:", metrics.accuracy_score(y_train, y_pred_train))

Accuracy on Training: 0.9748743718592965


In [ ]:
clf.support_vectors_.shape

(74, 30)

In [ ]:
clf.support_vectors_

array([[0.38466217, 0.41626298, 0.36695927, ..., 0.42130584, 0.31736645,
        0.36181757],
       [0.21029956, 0.28788927, 0.21593035, ..., 0.53127148, 0.63000197,
        0.72193964],
       [0.38922398, 0.4283737 , 0.37616923, ..., 0.50721649, 0.19534792,
        0.11224144],
       ...,
       [0.06781895, 0.24048443, 0.07821269, ..., 0.60137457, 0.52493594,
        0.52950153],
       [0.2746718 , 0.42076125, 0.28133544, ..., 0.38694158, 0.50522373,
        0.44557477],
       [0.2001622 , 0.27508651, 0.19607138, ..., 0.4185567 , 0.24462842,
        0.30459478]])

In [ ]:
clf.support_

array([ 17,  38,  58,  60,  87,  88, 100, 116, 137, 150, 161, 171, 184,
       188, 192, 198, 206, 225, 226, 238, 243, 262, 274, 276, 287, 297,
       318, 347, 352, 357, 363, 367, 368, 372, 385,  23,  33,  44,  67,
        74,  76,  77,  91,  94,  96, 102, 110, 112, 115, 117, 120, 124,
       152, 160, 170, 182, 183, 185, 196, 227, 242, 244, 263, 277, 282,
       285, 290, 316, 335, 356, 373, 376, 377, 391], dtype=int32)

In [ ]:
clf.n_support_

array([35, 39], dtype=int32)

In [ ]:
len(clf.support_)

74

In [ ]:
clf.coef_

array([[-1.22223498, -1.28169542, -1.11807393, -1.06765568, -0.3567051 ,
         0.31753915, -0.85340739, -1.20717282, -0.7550018 ,  0.81193256,
        -1.25594908, -0.38020738, -1.05016404, -0.74425197, -0.76176364,
         0.82942234,  0.07522007, -0.19703461,  0.05378627,  0.40831035,
        -1.78398339, -1.970372  , -1.6048979 , -1.32594014, -1.34498035,
        -0.17767574, -0.90651717, -1.51377904, -1.53934982, -0.18560617]])

In [ ]:
len(clf.coef_[0])

30

In [ ]:
clf.dual_coef_

array([[-1.        , -0.94097271, -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
         1.        ,  0.39732048,  1.        ,  1.        ,  0.00558856,
         1.        ,  1.        ,  0.29780072,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  0.23851685,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  0.76383167,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  0.98223264,
         1.        ,  1.        ,  1.        ,  1. 

In [ ]:
clf.dual_coef_.shape

(1, 74)

In [ ]:
len(clf.dual_coef_[0])

74

In [ ]:
clf.predict([X_train[1]])

array([1])

In [ ]:
clf.intercept_

array([6.25402963])

In [ ]:
clf.decision_function([X_train[0]])

array([-3.85412789])

In [ ]:
clf.dual_coef_ @ clf.support_vectors_

array([[-1.22223498, -1.28169542, -1.11807393, -1.06765568, -0.3567051 ,
         0.31753915, -0.85340739, -1.20717282, -0.7550018 ,  0.81193256,
        -1.25594908, -0.38020738, -1.05016404, -0.74425197, -0.76176364,
         0.82942234,  0.07522007, -0.19703461,  0.05378627,  0.40831035,
        -1.78398339, -1.970372  , -1.6048979 , -1.32594014, -1.34498035,
        -0.17767574, -0.90651717, -1.51377904, -1.53934982, -0.18560617]])

In [ ]:
(clf.dual_coef_ @ clf.support_vectors_).shape

(1, 30)

In [ ]:
X_train[0].reshape(1, len(X_train[0])).T

array([[0.19357291],
       [0.46885813],
       [0.19139445],
       [0.10001716],
       [0.36092805],
       [0.23706491],
       [0.26054358],
       [0.20402584],
       [0.16565657],
       [0.331508  ],
       [0.05226853],
       [0.71944114],
       [0.06589169],
       [0.01899148],
       [0.19439272],
       [0.25929508],
       [0.14489899],
       [0.24000758],
       [0.09846907],
       [0.13277504],
       [0.13895183],
       [0.66585695],
       [0.14127396],
       [0.06217745],
       [0.33001227],
       [0.232979  ],
       [0.2899361 ],
       [0.33171821],
       [0.10782574],
       [0.27365209]])

In [ ]:
X_train[0].reshape(1, len(X_train[0])).T.shape

(30, 1)

In [ ]:
((clf.dual_coef_ @ clf.support_vectors_) @ X_train[1].reshape(1, len(X_train[1])).T + clf.intercept_)[0][0]

2.6518997615998696

In [ ]:
!pip install z3-solver

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from z3 import *

In [ ]:
cancer.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [ ]:
cancer.target_names

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
dict_vars = {}
for feature in cancer.feature_names:
  dict_vars[feature] = Real(feature)

In [ ]:
dict_vars

{'area error': area error,
 'compactness error': compactness error,
 'concave points error': concave points error,
 'concavity error': concavity error,
 'fractal dimension error': fractal dimension error,
 'mean area': mean area,
 'mean compactness': mean compactness,
 'mean concave points': mean concave points,
 'mean concavity': mean concavity,
 'mean fractal dimension': mean fractal dimension,
 'mean perimeter': mean perimeter,
 'mean radius': mean radius,
 'mean smoothness': mean smoothness,
 'mean symmetry': mean symmetry,
 'mean texture': mean texture,
 'perimeter error': perimeter error,
 'radius error': radius error,
 'smoothness error': smoothness error,
 'symmetry error': symmetry error,
 'texture error': texture error,
 'worst area': worst area,
 'worst compactness': worst compactness,
 'worst concave points': worst concave points,
 'worst concavity': worst concavity,
 'worst fractal dimension': worst fractal dimension,
 'worst perimeter': worst perimeter,
 'worst radius': w

In [ ]:
dict_vars['area error']

area error

In [ ]:
constraints = Solver()

In [ ]:
constraints.add(dict_vars['area error'] > 2)
constraints.add(dict_vars['compactness error'] < 10)
constraints.add(dict_vars['compactness error'] > 2)
constraints.add(dict_vars['area error'] * dict_vars['compactness error'] == 27)

In [ ]:
constraints.assertions

<bound method Solver.assertions of [area error > 2,
 compactness error < 10,
 compactness error > 2,
 area error*compactness error == 27]>

In [ ]:
constraints.check()

sat

In [ ]:
constraints.model()

[compactness error = 3, area error = 9]

In [ ]:
np.RealVal = np.vectorize(RealVal) 
np.RealVector = np.vectorize(RealVector)

In [ ]:
z3_dual_coef = np.RealVal(clf.dual_coef_)
z3_support_vectors = np.RealVal(clf.support_vectors_)
z3_intercept_ = np.RealVal(clf.intercept_)
z3_X_Train = np.RealVector('x',X_train.shape[1])

In [ ]:
print(X_train)

[[0.19357291 0.46885813 0.19139445 ... 0.33171821 0.10782574 0.27365209]
 [0.3081251  0.1        0.28881854 ... 0.19938144 0.2479795  0.1093591 ]
 [0.48147397 0.40449827 0.45819542 ... 0.68178694 0.32544845 0.17514412]
 ...
 [0.22094379 0.42698962 0.22183048 ... 0.37525773 0.12339838 0.32595795]
 [0.64620609 0.39446367 0.61793064 ... 0.60652921 0.20579539 0.10435741]
 [0.20523088 0.14913495 0.204274   ... 0.3628866  0.20480978 0.37088844]]


In [ ]:
z3_X_Train

array([x__0, x__1, x__2, x__3, x__4, x__5, x__6, x__7, x__8, x__9, x__10,
       x__11, x__12, x__13, x__14, x__15, x__16, x__17, x__18, x__19,
       x__20, x__21, x__22, x__23, x__24, x__25, x__26, x__27, x__28,
       x__29], dtype=object)

In [ ]:
print(clf.predict(X_train[0:10]))

[1 1 0 1 0 1 1 0 1 1]


In [ ]:
def unfixed_list(X, z3_coef, z3_sup_vec, z3_X, z3_intercept, crescent_order=True,show_values=False):
    satisfatible = []
    unsatisfatible = []
    global_values = []
    print("Number of instances: ",len(X))
    if crescent_order:
        for i in [0, 7]:
          
          index_list = list(range(len(z3_X)))
          unsat_list = []
          sat_list = []
          values = []  

          print(X[i])
          print(clf.predict(X[i].reshape(1, -1)))
          
          for z in range(0, len(z3_X)):
            
            solver2 = Solver()
            if clf.predict(X[i].reshape(1, -1))[0] == 1:
              solver2.add(((z3_coef @ z3_sup_vec) @ z3_X.reshape(1, len(z3_X)).T + z3_intercept)[0][0] < 0)
            else:
              solver2.add(((z3_coef @ z3_sup_vec) @ z3_X.reshape(1, len(z3_X)).T + z3_intercept)[0][0] > 0)
            for j in range(0, len(z3_X)):
              solver2.add(z3_X[j] >=0)
              solver2.add(z3_X[j] <=1)
            used_list = []
            for j in range(0, len(z3_X)):
              if j != z and j in index_list: 
                solver2.add(z3_X[j] == X[i][j])
                
                used_list.append(j)

            check = solver2.check()
            
            if check == sat:         
              model = solver2.model()
              value = model[z3_X[z]].numerator_as_long()/model[z3_X[z]].denominator_as_long()
              sat_list.append(z)
              values.append(value)
              if show_values:  
                  print('i = ',i,z, check, X[i][j], value)
            else:
              unsat_list.append(z)
              index_list.remove(z)
              if show_values:
                  print('i = ',i, z, check)  
          print("Finished ",i)
          satisfatible.append(sat_list)
          unsatisfatible.append(unsat_list)
          global_values.append(values)
              
               
    for i in range(0, len(satisfatible)):
        print('Instância ',i,'\nSatisfatível: ', satisfatible[i],'\nValores: ',global_values,'\nInsatisfatível: ',unsatisfatible[i],'\n\n')
    return satisfatible, unsatisfatible

In [ ]:
simplify(((z3_dual_coef @ z3_support_vectors) @ z3_X_Train.reshape(1, len(z3_X_Train)).T + z3_intercept_)[0][0] < 0)

Not(-6254029628707463/1000000000000000 <=
    -61111748873313956668785345455226757/50000000000000000000000000000000000*
    x__0 +
    -12816954245912384551482741553966629/10000000000000000000000000000000000*
    x__1 +
    -13975924107855230714339406190220237/12500000000000000000000000000000000*
    x__2 +
    -10676556805469204237112814276247893/10000000000000000000000000000000000*
    x__3 +
    -17835254918666467611828071659227/50000000000000000000000000000000*
    x__4 +
    31753915498993993858736324632680057/100000000000000000000000000000000000*
    x__5 +
    -42670369559714728500478704117727403/50000000000000000000000000000000000*
    x__6 +
    -60358640907395192575405865022049111/50000000000000000000000000000000000*
    x__7 +
    -15100035999615379615472726827287193/20000000000000000000000000000000000*
    x__8 +
    8119325613937612178133984979419843/10000000000000000000000000000000000*
    x__9 +
    -125594907564116046640062497668162041/100000000000000000000000000000000000*
    x__10 +
    -3802073789245024183923665781071773/10000000000000000000000000000000000*
    x__11 +
    -26254100897316964386648601651608107/25000000000000000000000000000000000*
    x__12 +
    -14885039320412610542070848250966157/20000000000000000000000000000000000*
    x__13 +
    -76176364351246398483773413998640099/100000000000000000000000000000000000*
    x__14 +
    82942234386641174500566622858570103/100000000000000000000000000000000000*
    x__15 +
    7522007082081715372594581222903301/100000000000000000000000000000000000*
    x__16 +
    -3940692227008817199485643337811449/20000000000000000000000000000000000*
    x__17 +
    336164201929063807758417109851413/6250000000000000000000000000000000*
    x__18 +
    40831034984307331077458305621308699/100000000000000000000000000000000000*
    x__19 +
    -35679667813816821699132213814263977/20000000000000000000000000000000000*
    x__20 +
    -19703719987563788737445220572338239/10000000000000000000000000000000000*
    x__21 +
    -80244895044911721934532915994289959/50000000000000000000000000000000000*
    x__22 +
    -2651880274634187073094853932553877/2000000000000000000000000000000000*
    x__23 +
    -13449803499115253006011338850934679/10000000000000000000000000000000000*
    x__24 +
    -2220946690125996369179368055306231/12500000000000000000000000000000000*
    x__25 +
    -226629291737809634992898674058762753/250000000000000000000000000000000000*
    x__26 +
    -37844476091317284880230566668887799/25000000000000000000000000000000000*
    x__27 +
    -76967491016665805832135872941179697/50000000000000000000000000000000000*
    x__28 +
    -18560616914220296727078204458590847/100000000000000000000000000000000000*
    x__29)

In [ ]:
satisfatible, unsatisfatible = unfixed_list(X_train,z3_dual_coef,z3_support_vectors,z3_X_Train,z3_intercept_,crescent_order=True, show_values=False)

Number of instances:  398
[0.19357291 0.46885813 0.19139445 0.10001716 0.36092805 0.23706491
 0.26054358 0.20402584 0.16565657 0.331508   0.05226853 0.71944114
 0.06589169 0.01899148 0.19439272 0.25929508 0.14489899 0.24000758
 0.09846907 0.13277504 0.13895183 0.66585695 0.14127396 0.06217745
 0.33001227 0.232979   0.2899361  0.33171821 0.10782574 0.27365209]
[1]
Finished  0
[0.63708247 0.43771626 0.60785725 0.46923539 0.34440733 0.32862966
 0.34325211 0.43156064 0.52272727 0.13753159 0.26528434 0.32490525
 0.21220589 0.15141633 0.11766153 0.30765659 0.10686869 0.24038644
 0.26295942 0.12147783 0.56801403 0.51551957 0.5165472  0.37872171
 0.25203956 0.34721617 0.32731629 0.54054983 0.41868717 0.24279417]
[0]
Finished  7
Instância  0 
Satisfatível:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] 
Valores:  [[1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.925318832930145, 1.0, 0.9661872834115504,